[package]
name = "quartz_os"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]

[[bin]]
name = "quartz_os"
test = false
bench = false
