[package]
name = "quartz_os"
version = "0.1.0"
edition = "2024"
authors = ["IchoDev <johnathontech@gmail.com>"]

[[bin]]
name = "quartz_os"
test = false
bench = false

[dependencies]
bootloader = "0.9"