[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-quartz_os.json"

[target.x86_64-quartz_os]
linker = "rust-lld"

# Disable build scripts to avoid host linker dependencies
[target.x86_64-pc-windows-msvc]
linker = "rust-lld"